CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
LATENT_IMAGE_TOKEN_INDEX = -300
INSTRUCT_INDEX = -400

DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_LATENT_IMAGE_TOKEN = "<latent_image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<vision_start>"
DEFAULT_IM_END_TOKEN = "<vision_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"
